const PATTERNS: Record<MoveMatch, RegExp[]> = {
    match4: [/aooo/, /oaoo/, /ooao/, /oooa/],
    match3: [
        /a[^x]oo/,
        /ao[^x]o/,
        /aoo[^x]/,
        /[^x]aoo/,
        /[^x]oao/,
        /[^x]ooa/,
        /oa[^x]o/,
        /oao[^x]/,
        /o[^x]ao/,
        /o[^x]oa/,
        /ooa[^x]/,
        /oo[^x]a/,
    ],
    match2: [
        /a[^x]{2}o/,
        /a[^x]o[^x]/,
        /ao[^x]{2}/,
        /[^x]a[^x]o/,
        /[^x]ao[^x]/,
        /[^x]{2}ao/,
        /[^x]{2}oa/,
        /[^x]oa[^x]/,
        /[^x]o[^x]a/,
        /oa[^x]{2}/,
        /o[^x]a[^x]/,
        /o[^x]{2}a/,
    ],
    match4Next: [/nooo/, /onoo/, /oono/, /ooon/],
    match3Next: [
        /n[^x]oo/,
        /no[^x]o/,
        /noo[^x]/,
        /[^x]noo/,
        /[^x]ono/,
        /[^x]oon/,
        /on[^x]o/,
        /ono[^x]/,
        /o[^x]no/,
        /o[^x]on/,
        /oon[^x]/,
        /oo[^x]n/,
    ],
    match2Next: [
        /n[^x]{2}o/,
        /n[^x]o[^x]/,
        /no[^x]{2}/,
        /[^x]n[^x]o/,
        /[^x]no[^x]/,
        /[^x]{2}no/,
        /[^x]{2}on/,
        /[^x]on[^x]/,
        /[^x]o[^x]n/,
        /on[^x]{2}/,
        /o[^x]n[^x]/,
        /o[^x]{2}n/,
    ],
};
